# DS-I Africa Deep Learning Course - 4 July 2023
## Mandla Gwetu (mvgcollab@gmail.com)

In [1]:
import numpy as np
from keras import Sequential, layers, optimizers, models
from sklearn.model_selection import train_test_split
import os

## Many to One Sequence Generator

In [2]:
num_max = 105
s_size = 5
n = num_max - s_size # number of instances
f_size = 1
o_size = 1

In [3]:
def many2one_gen():
  file_x = open('many2one_x.txt','w')
  file_y = open('many2one_y.txt','w')
  for i in range(s_size,num_max):
    for j in range(i-s_size,i):
      file_x.write(str(j)+' ')
    if i!=num_max-1:
      file_x.write('\n')
    if i==num_max-1:
      file_y.write(str(i))
    else:
      file_y.write(str(i)+'\n')
  file_x.close()
  file_y.close()

In [4]:
many2one_gen()

In [5]:
h_state_size = 20
model1 = Sequential()
model1.add(layers.SimpleRNN(h_state_size, input_shape=(s_size, f_size), activation='relu', return_sequences=False))
model1.add(layers.Dense(o_size))
model1.compile(loss="mean_squared_error", optimizer='adam')
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 20)                440       
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 461 (1.80 KB)
Trainable params: 461 (1.80 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
X1 = np.loadtxt('many2one_x.txt')
print(X1.shape)
X1 = X1.reshape(n,s_size,f_size)
print(X1.shape)

(100, 5)
(100, 5, 1)


In [7]:
y1 = np.loadtxt('many2one_y.txt')
print(y1.shape)
y1 = y1.reshape(n,o_size)
print(y1.shape)

(100,)
(100, 1)


In [8]:
test_prop = 0.25
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,y1,random_state=1,test_size=test_prop,shuffle=True)

model1.fit(X1_train, y1_train, epochs=1000, verbose=2)

Epoch 1/1000
3/3 - 1s - loss: 1734.6763 - 1s/epoch - 391ms/step
Epoch 2/1000
3/3 - 0s - loss: 1503.0923 - 11ms/epoch - 4ms/step
Epoch 3/1000
3/3 - 0s - loss: 1244.3163 - 18ms/epoch - 6ms/step
Epoch 4/1000
3/3 - 0s - loss: 1026.1416 - 12ms/epoch - 4ms/step
Epoch 5/1000
3/3 - 0s - loss: 808.1992 - 12ms/epoch - 4ms/step
Epoch 6/1000
3/3 - 0s - loss: 601.7848 - 11ms/epoch - 4ms/step
Epoch 7/1000
3/3 - 0s - loss: 418.5825 - 11ms/epoch - 4ms/step
Epoch 8/1000
3/3 - 0s - loss: 269.6402 - 11ms/epoch - 4ms/step
Epoch 9/1000
3/3 - 0s - loss: 154.8766 - 11ms/epoch - 4ms/step
Epoch 10/1000
3/3 - 0s - loss: 62.2496 - 11ms/epoch - 4ms/step
Epoch 11/1000
3/3 - 0s - loss: 18.1990 - 20ms/epoch - 7ms/step
Epoch 12/1000
3/3 - 0s - loss: 3.1298 - 13ms/epoch - 4ms/step
Epoch 13/1000
3/3 - 0s - loss: 10.4072 - 14ms/epoch - 5ms/step
Epoch 14/1000
3/3 - 0s - loss: 24.7143 - 13ms/epoch - 4ms/step
Epoch 15/1000
3/3 - 0s - loss: 32.6083 - 14ms/epoch - 5ms/step
Epoch 16/1000
3/3 - 0s - loss: 29.3103 - 13ms/epoch 

In [9]:
wx1 = model1.get_weights()[0]
wh1 = model1.get_weights()[1]
bh1 = model1.get_weights()[2]
wy1 = model1.get_weights()[3]
by1 = model1.get_weights()[4]

print('Input Weights:', "==========================", wx1,sep='\n')
print('Hidden State Weights:', "==========================", wh1,sep='\n')
print('Hidden State Biases:', "==========================", bh1,sep='\n')
print('Output Weights:', "==========================", wy1,sep='\n')
print('Output Biases:', "==========================", by1,sep='\n')

Input Weights:
[[-0.11845166 -0.5074523   0.25841612  0.0757269  -0.2526938  -0.51093495
  -0.5081403   0.25329936  0.271443    0.25026923 -0.46576026  0.39940572
  -0.307573    0.34065607  0.44379804  0.44933543  0.51195234 -0.5019674
  -0.4215941   0.2949569 ]]
Hidden State Weights:
[[ 8.95891637e-02 -5.51132187e-02  4.31697786e-01 -2.12636143e-01
  -5.30770183e-01  9.41555202e-02 -2.48671472e-01 -2.11179882e-01
  -2.87491977e-01  8.20143819e-02 -8.00316855e-02 -8.14235676e-03
   2.62443088e-02  3.49630445e-01  1.64021164e-01  2.52837330e-01
   2.81946547e-02 -5.06574102e-02  4.04454499e-01  2.09451141e-03]
 [ 3.98918122e-01 -3.06568563e-01  1.53115094e-01 -1.40876800e-01
   1.55253708e-02  1.95327803e-01  1.52910322e-01 -1.46576166e-01
   1.12460628e-02 -3.95563722e-01 -7.86492079e-02  8.18530396e-02
   7.91921243e-02  1.58132479e-01 -2.25015610e-01 -1.79398701e-01
  -3.80391538e-01  2.73004115e-01 -1.58355847e-01 -3.04052681e-01]
 [ 2.94175595e-01  1.13401450e-01 -2.45177016e-01 -6

In [10]:
y1_test_ = np.rint(model1.predict(X1_test))
acc1 = np.sum(y1_test == y1_test_)/len(y1_test)*100
print('Accuraccy:',acc1,'%')
print(y1_test[:5])
print(y1_test_[:5])

1/1 [==============================] - 0s 261ms/step
Accuraccy: 100.0 %
[[85.]
 [89.]
 [38.]
 [86.]
 [98.]]
[[85.]
 [89.]
 [38.]
 [86.]
 [98.]]


## One to Many Sequence Generator

In [11]:
s_size = 1
o_size = 5
def one2many_gen():
  file_x = open('one2many_x.txt','w')
  file_y = open('one2many_y.txt','w')
  for i in range(num_max-o_size):
    for j in range(i+1,i+1+o_size):
      file_y.write(str(j)+' ')
      if j==i+o_size and i!=num_max-o_size-1:
        file_y.write('\n')
    if i==num_max-o_size-1:
      file_x.write(str(i))
    else:
      file_x.write(str(i)+'\n')
  file_x.close()
  file_y.close()

In [12]:
one2many_gen()

In [20]:
h_state_size = 50
model2 = Sequential()
model2.add(layers.SimpleRNN(h_state_size, input_shape=(s_size, f_size), activation='relu', return_sequences=False))
model2.add(layers.Dense(o_size))
model2.compile(loss="mean_squared_error", optimizer='adam')
model2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 50)                2600      
                                                                 
 dense_2 (Dense)             (None, 5)                 255       
                                                                 
Total params: 2855 (11.15 KB)
Trainable params: 2855 (11.15 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
X2 = np.loadtxt('one2many_x.txt')
print(X2.shape)
X2 = X2.reshape(n,s_size,f_size)
print(X2.shape)

(100,)
(100, 1, 1)


In [22]:
y2 = np.loadtxt('one2many_y.txt')
print(y2.shape)
y2 = y2.reshape(n,o_size)
print(y2.shape)

(100, 5)
(100, 5)


In [23]:
test_prop = 0.25
X2_train, X2_test, y2_train, y2_test = train_test_split(X2,y2,random_state=1,test_size=test_prop,shuffle=True)

model2.fit(X2_train, y2_train, epochs=1000, verbose=2)


Epoch 1/1000
3/3 - 1s - loss: 2648.2615 - 1s/epoch - 485ms/step
Epoch 2/1000
3/3 - 0s - loss: 2547.9326 - 12ms/epoch - 4ms/step
Epoch 3/1000
3/3 - 0s - loss: 2446.1172 - 11ms/epoch - 4ms/step
Epoch 4/1000
3/3 - 0s - loss: 2352.5259 - 20ms/epoch - 7ms/step
Epoch 5/1000
3/3 - 0s - loss: 2255.7239 - 15ms/epoch - 5ms/step
Epoch 6/1000
3/3 - 0s - loss: 2158.9888 - 13ms/epoch - 4ms/step
Epoch 7/1000
3/3 - 0s - loss: 2070.1348 - 12ms/epoch - 4ms/step
Epoch 8/1000
3/3 - 0s - loss: 1975.8860 - 14ms/epoch - 5ms/step
Epoch 9/1000
3/3 - 0s - loss: 1886.7164 - 13ms/epoch - 4ms/step
Epoch 10/1000
3/3 - 0s - loss: 1795.8071 - 12ms/epoch - 4ms/step
Epoch 11/1000
3/3 - 0s - loss: 1713.9086 - 15ms/epoch - 5ms/step
Epoch 12/1000
3/3 - 0s - loss: 1626.5735 - 17ms/epoch - 6ms/step
Epoch 13/1000
3/3 - 0s - loss: 1541.1719 - 13ms/epoch - 4ms/step
Epoch 14/1000
3/3 - 0s - loss: 1461.6787 - 10ms/epoch - 3ms/step
Epoch 15/1000
3/3 - 0s - loss: 1376.8274 - 11ms/epoch - 4ms/step
Epoch 16/1000
3/3 - 0s - loss: 130

In [24]:
wx2 = model2.get_weights()[0]
wh2 = model2.get_weights()[1]
bh2 = model2.get_weights()[2]
wy2 = model2.get_weights()[3]
by2 = model2.get_weights()[4]

In [25]:
print('Input Weights:', "==========================", wx2,sep='\n')
print('Hidden State Weights:', "==========================", wh2,sep='\n')
print('Hidden State Biases:', "==========================", bh2,sep='\n')
print('Output Weights:', "==========================", wy2,sep='\n')
print('Output Biases:', "==========================", by2,sep='\n')

Input Weights:
[[-0.14737742  0.1893161  -0.12698546  0.451722   -0.09347802  0.12784855
  -0.13822168 -0.03910613 -0.02380058  0.19319999 -0.15159261  0.20921485
  -0.1472016  -0.07676062  0.4085085   0.26650956 -0.01348159  0.47521237
  -0.28252837 -0.22280246 -0.24714696  0.18997204  0.12184268  0.2704424
  -0.30888933 -0.19087088 -0.21846443  0.15214975 -0.11733332 -0.16068612
  -0.03052771  0.2186562  -0.00999525 -0.03585893  0.20832689  0.3309618
  -0.05591455  0.40566686 -0.3128834  -0.00911152  0.4178622   0.44176784
  -0.15069978 -0.2953663   0.30488488  0.12568575 -0.00241778 -0.14094493
   0.14240836  0.42297497]]
Hidden State Weights:
[[ 0.19310045  0.10748137 -0.12426692 ...  0.1063932   0.00162196
  -0.10884373]
 [ 0.0820423  -0.08459842 -0.17296822 ... -0.25530303  0.06554672
   0.09848563]
 [ 0.21964914 -0.02121239 -0.09359741 ...  0.33629754 -0.09662561
  -0.16591322]
 ...
 [ 0.02349675  0.10305034 -0.11939935 ... -0.04986955  0.02238916
   0.23056646]
 [-0.07808236  0

In [26]:
y2_test_ = np.rint(model2.predict(X2_test))
acc2 = np.sum(y2_test == y2_test_)/(o_size*len(y2_test))*100
print('Accuraccy:',acc2,'%')
print(y2_test[:5])
print(y2_test_[:5])

1/1 [==============================] - 0s 142ms/step
Accuraccy: 79.2 %
[[81. 82. 83. 84. 85.]
 [85. 86. 87. 88. 89.]
 [34. 35. 36. 37. 38.]
 [82. 83. 84. 85. 86.]
 [94. 95. 96. 97. 98.]]
[[81. 82. 83. 84. 85.]
 [85. 86. 87. 88. 90.]
 [34. 35. 36. 36. 37.]
 [82. 83. 84. 85. 86.]
 [94. 95. 96. 97. 99.]]


## Exercise
Separate this notebook into two separate notebooks: focusing on many-to-one and one-to-many examples, respectively. Try and see if you can find models with training losses that are less than 0.001 at the end of all the epochs.  Can you explain the dimensions of the weight matrices?